upstream api_upstream {
    server app-replica1:8080;
    server app-replica2:8080;
    server app-replica3:8080;
}

server {
    listen 80;

    add_header X-Upstream-Addr $upstream_addr always;

    location / {
        proxy_pass http://api_upstream;
        proxy_http_version 1.1;
        proxy_set_header Connection "close";
    }
}